apiVersion: apps/v1
kind: Deployment
metadata:
  name: step1-backend-deployment
spec:
  selector:
    matchLabels:
      app: step1-backend-deployment
  template:
    metadata:
      labels:
        app: step1-backend-deployment
    spec:
      containers:
        - name: step1-backend-deployment
          image: shieldxbot/backend_exemple:Docker_version
          workingDir: /app
          command: ["node", "dist/index.js"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
      restartPolicy: Always
