apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: step2-backend-ingress
  labels:
    app.kubernetes.io/name: myingress
  annotations:
    kubernetes.io/ingress.class: public
spec:
  ingressClassName: public
  rules:
    - host: shieldx-app.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: step2-backend-service
                port:
                  number: 3000
