apiVersion: v1
kind: Service
metadata:
  name: step2-backend-service
spec:
  type: NodePort
  selector:
    app: step2-backend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
